name: Deploy calculator-api Docker App to AWS EC2

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: calculator
  CONTAINER_NAME: calculator-container
  INSTANCE_TYPE: t2.micro
  AMI_ID: ami-0c398cb65a93047f2
  KEY_NAME: calsi-key
  INSTANCE_NAME: calculator
  SECURITY_GROUP_NAME: launch-wizard-3
  SECURITY_GROUP_DESCRIPTION: "launch-wizard-3 created via GitHub Actions"
  VPC_ID: vpc-0d1bf1da3a43aa0bd
  EIP_ALLOCATION_ID: eipalloc-06dff942a3830aac8
  ECR_ROLE_NAME: ec2-ecr-access-role

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::575327645493:role/ec2-ecr-access-role

      - name: Check if Security Group Exists
        id: check-security-group
        run: |
            SECURITY_GROUP_ID=$(aws ec2 describe-security-groups \
              --filters Name=group-name,Values=${{ env.SECURITY_GROUP_NAME }} \
              --query 'SecurityGroups[0].GroupId' \
              --output text)

            if [ "$SECURITY_GROUP_ID" == "None" ]; then
              echo "security_group_exists=false" >> $GITHUB_ENV
            else
              echo "security_group_exists=true" >> $GITHUB_ENV
              echo "security_group_id=$SECURITY_GROUP_ID" >> $GITHUB_ENV
            fi

      - name: Create Security Group
        if: env.security_group_exists == 'false'
        run: |
          SG_ID=$(aws ec2 create-security-group \
            --group-name ${{ env.SECURITY_GROUP_NAME }} \
            --description "${{ env.SECURITY_GROUP_DESCRIPTION }}" \
            --vpc-id ${{ env.VPC_ID }} \
            --query 'GroupId' --output text)
          echo "security_group_id=$SG_ID" >> $GITHUB_ENV

      - name: Approve inbound rules
        run: |
          PORTS="22 80 443 9000"
          for PORT in $PORTS; do
            aws ec2 authorize-security-group-ingress \
              --group-id ${{ env.security_group_id }} \
              --protocol tcp --port $PORT --cidr 0.0.0.0/0 || true
          done

      - name: Check if EC2 Instance Exists
        run: |
          ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=${{ env.INSTANCE_NAME }}" "Name=instance-state-name,Values=running" \
            --query 'Reservations[0].Instances[0].InstanceId' \
            --output text)

          if [ "$ID" = "None" ]; then
            echo "instance_exists=false" >> $GITHUB_ENV
          else
            echo "instance_exists=true" >> $GITHUB_ENV
            echo "instance_id=$ID" >> $GITHUB_ENV
          fi

      - name: Create EC2 instance if missing
        if: env.instance_exists == 'false'
        run: |
          ID=$(aws ec2 run-instances \
            --image-id ${{ env.AMI_ID }} \
            --count 1 \
            --instance-type ${{ env.INSTANCE_TYPE }} \
            --key-name ${{ env.KEY_NAME }} \
            --network-interfaces '[{"AssociatePublicIpAddress":true,"DeviceIndex":0,"Groups":["${{ env.security_group_id }}"]}]' \
            --iam-instance-profile Name=${{ env.ECR_ROLE_NAME }} \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=${{ env.INSTANCE_NAME }}}]' \
            --query 'Instances[0].InstanceId' --output text)
          echo "instance_id=$ID" >> $GITHUB_ENV

      - name: Wait for instance to be running
        run: aws ec2 wait instance-running --instance-ids ${{ env.instance_id }}

      - name: Fetch Public IP
        run: |
          IP=$(aws ec2 describe-instances \
            --instance-ids ${{ env.instance_id }} \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          echo "public_ip=$IP" >> $GITHUB_ENV

      - name: Associate Elastic IP
        run: |
          aws ec2 associate-address --instance-id ${{ env.instance_id }} --allocation-id ${{ env.EIP_ALLOCATION_ID }}
          IP=$(aws ec2 describe-addresses --allocation-ids ${{ env.EIP_ALLOCATION_ID }} --query 'Addresses[0].PublicIp' --output text)
          echo "public_ip=$IP" >> $GITHUB_ENV

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build and push Docker image
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/${{ env.ECR_REPOSITORY }}:$TAG .
          docker push $REGISTRY/${{ env.ECR_REPOSITORY }}:$TAG
          echo "image=$REGISTRY/${{ env.ECR_REPOSITORY }}:$TAG" >> $GITHUB_OUTPUT

      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ env.public_ip }} << EOF

          sudo apt-get update -y
          sudo apt-get install -y docker.io nginx

          sudo systemctl enable docker
          sudo systemctl start docker

          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          TAG="${{ github.sha }}"

          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin \$REGISTRY

          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true

          docker pull \$REGISTRY/${{ env.ECR_REPOSITORY }}:\$TAG

          sudo tee /etc/systemd/system/${{ env.CONTAINER_NAME }}.service > /dev/null << EOL
          [Unit]
          Description=Calculator API Container
          After=network.target docker.service
          Requires=docker.service

          [Service]
          Restart=always
          ExecStart=/usr/bin/docker run --name ${{ env.CONTAINER_NAME }} -p 9000:9000 \$REGISTRY/${{ env.ECR_REPOSITORY }}:\$TAG
          ExecStop=/usr/bin/docker stop ${{ env.CONTAINER_NAME }}

          [Install]
          WantedBy=multi-user.target
          EOL

          sudo systemctl daemon-reload
          sudo systemctl enable ${{ env.CONTAINER_NAME }}
          sudo systemctl restart ${{ env.CONTAINER_NAME }}

          sudo bash -c "cat > /etc/nginx/sites-available/${{ env.CONTAINER_NAME }}" << EOL
          server {
               listen 80;
                server_name prasath.praveenm.me;

          location / {
                  proxy_pass http://localhost:9000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
            }
          EOL

          sudo rm -f /etc/nginx/sites-enabled/default
          sudo ln -sf /etc/nginx/sites-available/${{ env.CONTAINER_NAME }} /etc/nginx/sites-enabled/

          sudo nginx -t
          sudo systemctl restart nginx

          EOF
